config/routes.rb
Rails.application.routes.draw do

  # team
  resources :teams, only: [:show] do 
    collection do 
      get 'list'
    end
  end
  
  # project
  resources :projects, only: [:show] do 
    collection do 
      get 'list'
    end 
  end 

  namespace :project do
    resources :todo_lists, only: [:show]
    resources :todos, except: [:new]
  end

  # users (show-only)
  resources :users, only: [:show] do 
    collection do 
      get 'profile'
    end
  end
  
  # comments (show and create)
  resources :comments, only: [:show, :create]

  # events (list-only)
  resources :events, only: [:index]

  # 
  root 'events#index'
  
end

app/models/project.rb
class Project < ApplicationRecord

  include ProjectAccessConcerns  
  include OriginrelatedProtocol
  include MemberConcerns

  self.inheritance_column = nil

  enum type: {
    'standard' => 0,
    'board'    => 1,
  }

  belongs_to :team

  has_many :members,        class_name: 'Project::Member',       dependent: :destroy
  has_many :todo_lists,     class_name: 'Project::TodoList',     dependent: :destroy
  has_many :related_events, class_name: 'Event', as: :originrelated, dependent: :destroy

  validates :team_id, :name, :type, :is_private, :status, :presence => true
  validates :type, inclusion: types.keys


  # OriginrelatedProtocol

  def origin
    self
  end
  
  def origin_name
    self.name
  end

end

app/models/project/member.rb
class Project::Member < ApplicationRecord

  belongs_to :project
  belongs_to :user

  has_many :roles, class_name: 'Project::Member::Role', dependent: :destroy

  validates :project_id, :user_id, :presence => true
  validates :user_id, uniqueness: { scope: :project_id }
  
end

app/models/project/member/role.rb
class Project::Member::Role < ProjectBase

  self.inheritance_column = nil
  
  enum type: {
    'unset'               => 0,
    'frontend_developer'  => 1,
    'backend_developer'   => 2,
    'ui_designer'         => 3,
    'project_manager'     => 4,
  }
  
  belongs_to :member, class_name: 'Project::Member'

  has_many :accesses, as: :accessrelated,  dependent: :destroy

  validates :member_id, :type, :presence => true
  validates :type, inclusion: types.keys

  def project
    return nil if member.nil?
    member.project
  end

  def name
    return type.to_s
  end

end

app/models/project/todo.rb
class Project::Todo < ProjectBase

  include TodoConcerns
  include EventrelatedProtocol

  belongs_to :todo_list, class_name: 'Project::TodoList'

  has_many :todo_items, class_name: 'Project::TodoItem', dependent: :destroy
  has_many :comments, as: :commentable,  dependent: :destroy
  has_many :related_events, class_name: 'Event', as: :eventrelated, dependent: :destroy

  belongs_to :assigned_to_member, class_name: 'User', optional: true

  validates :todo_list_id, :content, :presence => true

  # model-action's callbacks

  after_create  :did_create
  after_destroy :did_destroy
  after_update  :did_update

  after_initialize :init

  def init
    self.completed = false if (self.has_attribute? :completed) && self.completed.nil?
    self.trashed   = false if (self.has_attribute? :trashed) && self.trashed.nil?

    # self.string ||= 'foo'  # will set the default value only if it's nil
    # self.number ||= 0.0 if self.has_attribute? :number
    # self.bool_field = true if (self.has_attribute? :bool_value) && self.bool_field.nil?
  end

  # ProjectBase

  def project
    return nil if todo_list.nil?
    todo_list.project
  end

  # EventrelatedProtocol

  def self.self_description
    I18n.t(self.name)
  end
  
  def event_target
    self
  end

  def event_title
    title
  end

  # CommentableProtocol

  def comment_title
    title
  end  

  # 

  def title
    content[0..20]
  end

  def completed_status
    completed ? 'Yes' : '-'
  end

  def trashed_status
    trashed ? 'Yes' : '-'
  end

end

app/models/project/todo_item.rb
class Project::TodoItem < ProjectBase

  belongs_to :todo, class_name: 'Project::Todo'

  validates :todo_id, :description, :presence => true

  def project
    return nil if todo.nil?
    todo.project
  end

end

app/models/project/todo_list.rb
class Project::TodoList < ProjectBase

  belongs_to :project
  
  has_many :todos, class_name: 'Project::Todo', dependent: :destroy

  validates :project_id, :name, :presence => true

end

app/controllers/project/todo_lists_controller.rb
class Project::TodoListsController < ProjectBaseController

  before_action :set_project_todo_list, only: [:show]

  def show
    @title = "TodoList/Show - #{@todo_list.name}"
    @todo = Project::Todo.new(todo_list: @todo_list)
    @member_hash = @todo.project.member_hash || {}
  end

  private

    def set_project_todo_list
      @todo_list = Project::TodoList.find(params[:id])
    end

end

app/controllers/project/todos_controller.rb
class Project::TodosController < ProjectBaseController
  
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @title = "Todos"

    @todo_hash = {}
    count = params[:count]
    count = (1..100).include?(count) ? count : 100

    projects = current_user.projects || []
    projects.each do |project|
      todo_lists = project.todo_lists
      next if todo_lists.nil?

      @todo_hash[project] = {}
      todo_lists.each do |todo_list|
        @todo_hash[project][todo_list] = todo_list.todos.order(:updated_at => 'DESC').limit(count)
      end
    end
  end

  def show
    @title = "Todo/Show - #{@todo.id}"
    @comment = Comment.new({
      user_id: current_user,
      commentable: @todo,
    })
    @comments = Comment.where(commentable: @todo, status: 0)
  end

  def edit
    @title = "Todo/Edit - #{@todo.id}"

    @member_hash = @todo.project.member_hash || {}
  end

  def create
    @todo = Project::Todo.new(todo_params_for_create)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :index }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @member_hash = @todo.project.member_hash || {}
    respond_to do |format|
      if @todo.update(todo_params_for_update)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @todo.destroy
        format.html { redirect_to project_todos_url, notice: 'Todo was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to project_todos_url, notice: @todo.errors.any? ? @todo.errors.full_messages.join('. ') : 'Todo destroy error.' }
        format.json { head 400 }
      end
    end
  end

  private
    
    def set_todo
      @todo = Project::Todo.find(params[:id])
    end

    def todo_params_for_create
      params.require(:project_todo).permit(:todo_list_id, :content, :assigned_to_member_id, :deadline, :completed, :trashed)
    end

    def todo_params_for_update
      params.require(:project_todo).permit(:content, :assigned_to_member_id, :deadline, :completed, :trashed)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ProjectBaseController
  
  before_action :set_project, only: [:show]
  before_action :check_access_permission, only: [:show]

  def list
    @title = "Project/List"

    @projects = current_user.projects || []
  end

  def show
    @title = "Project/Show - #{@project.name}"
  end

  private
    
    def set_project
      @project = Project.find(params[:id])
    end
    
end

app/helpers/project/todo_helper.rb
module Project::TodoHelper
end

app/views/project/todos/_form_for_edit.html.erb
<%= form_with(model: todo, local: true) do |form| %>

  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content, id: :todo_content, class: 'textarea', placeholder: 'Type your todo contents here' %>
  </div>

  <div class="field">
    <%= form.label :assigned_to_member_id %> <br>
    <%= form.select :assigned_to_member_id, options_for_select(member_hash, todo.assigned_to_member_id), prompt: 'Assign to a member?', id: :todo_assigned_to_member_id %>
  </div>

  <div class="field">
    <%= form.label :deadline %> <br>
    <%= form.number_field :deadline, id: :todo_deadline %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed, id: :todo_completed %>
  </div>

  <div class="field">
    <%= form.label :trashed %>
    <%= form.check_box :trashed, id: :todo_trashed %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/project/todos/_form_for_new_comment.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content, id: :comment_content, class: 'textarea', placeholder: 'Wanna say something?' %>
  </div>

  <div class="field">
    <%= form.hidden_field :commentable_id, id: :comment_commentable_id %>
  </div>

  <div class="field">
    <%= form.hidden_field :commentable_type, id: :comment_commentable_type %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/project/todos/_todo.html.erb
<div class="todo" data-todo-id="<%= todo.id %>">

  <div class="todo-content">
    <%= link_to(todo.title, todo, :target => :_blank) %>
  </div>

</div>

app/views/project/todos/_todo_row.html.erb
<tr>
  <td><%= todo.id %></td>
  <td><%= link_to(todo.title, todo) %></td>
  <td>
    <% if not todo.assigned_to_member_id.nil? %>
      <%= link_to(
        todo.assigned_to_member.display_name, 
        todo.assigned_to_member, 
        :target => :_blank) 
      %>
    <% else %>
      -
    <% end %>
  </td>
  <td>
    <% if todo.deadline.present? %>
      <%= format_timestamp(todo.deadline) %>
    <% else %>
      -
    <% end %>
  </td>
  <td><%= todo.completed_status %></td>
  <td><%= link_to 'Edit', edit_project_todo_path(todo) %></td>
  <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/project/todos/edit.html.erb
<%= render 'form_for_edit', todo: @todo, member_hash: @member_hash %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', project_todos_path %>

app/views/project/todos/index.html.erb
<p id="notice"><%= notice %></p>

<table class="records-table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Content</th>
      <th>Assignd to</th>
      <th>Deadline</th>
      <th>Completed</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>

    <% if not @todo_hash.nil? %>
    <% @todo_hash.each do |project, todo_list_hash| %>

      <% if not todo_list_hash.nil? %>
      <% todo_list_hash.each do |todo_list, todos| %>

        <% if not todos.nil? %>
        <% todos.each do |todo| %>
          <%= render partial: 'todo_row', locals: {project: project, todo_list: todo_list, todo: todo} %> 
        <% end %>
        <% end %>

      <% end %>  
      <% end %>

    <% end %>
    <% end %>

  </tbody>
</table>

<br>

app/views/project/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<p>
  <strong>Assignd to:</strong>
  <% if not @todo.assigned_to_member_id.nil? %>

    <%= link_to(
      @todo.assigned_to_member.display_name, 
      @todo.assigned_to_member, 
      :target => :_blank) 
    %>
    
  <% else %>
    -
  <% end %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @todo.deadline %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed_status %>
</p>

<p>
  <strong>Belongs to list:</strong>
  
  <%= link_to(
    @todo.todo_list.name, 
    @todo.todo_list, 
    :target => :_blank) 
  %>

</p>

<%= link_to 'Edit', edit_project_todo_path(@todo) %>

<hr>

<div id="comment-list">
  <% if not @comments.nil? %>
  <%= render @comments %>
  <% end %>
</div>

<div>
  <%= render 'form_for_new_comment', comment: @comment %>
</div>